/*
 * Attio API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@attio.com
 * Generated by: https://openapi-generator.tech
 */


use reqwest;

use crate::apis::ResponseContent;
use super::{Error, configuration};

/// struct for passing parameters to the method [`v2_tasks_get`]
#[derive(Clone, Debug)]
pub struct V2TasksGetParams {
    pub limit: Option<i32>,
    pub offset: Option<i32>,
    pub linked_object: Option<String>,
    pub linked_record_id: Option<String>
}

/// struct for passing parameters to the method [`v2_tasks_post`]
#[derive(Clone, Debug)]
pub struct V2TasksPostParams {
    pub v2_tasks_post_request: crate::models::V2TasksPostRequest
}

/// struct for passing parameters to the method [`v2_tasks_task_id_delete`]
#[derive(Clone, Debug)]
pub struct V2TasksTaskIdDeleteParams {
    pub task_id: String
}

/// struct for passing parameters to the method [`v2_tasks_task_id_get`]
#[derive(Clone, Debug)]
pub struct V2TasksTaskIdGetParams {
    pub task_id: String
}


/// struct for typed errors of method [`v2_tasks_get`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum V2TasksGetError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`v2_tasks_post`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum V2TasksPostError {
    Status400(crate::models::V2TasksPost400Response),
    Status404(crate::models::V2ObjectsObjectGet404Response),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`v2_tasks_task_id_delete`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum V2TasksTaskIdDeleteError {
    Status404(crate::models::V2TasksTaskIdGet404Response),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`v2_tasks_task_id_get`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum V2TasksTaskIdGetError {
    Status404(crate::models::V2TasksTaskIdGet404Response),
    UnknownValue(serde_json::Value),
}


/// List all tasks. Results are sorted by creation date, from oldest to newest.  Required scopes: `task:read`, `object_configuration:read`, `record_permission:read`, `user_management:read`.
pub async fn v2_tasks_get(configuration: &configuration::Configuration, params: V2TasksGetParams) -> Result<crate::models::V2TasksGet200Response, Error<V2TasksGetError>> {
    let local_var_configuration = configuration;

    // unbox the parameters
    let limit = params.limit;
    let offset = params.offset;
    let linked_object = params.linked_object;
    let linked_record_id = params.linked_record_id;


    let local_var_client = &local_var_configuration.client;

    let local_var_uri_str = format!("{}/v2/tasks", local_var_configuration.base_path);
    let mut local_var_req_builder = local_var_client.request(reqwest::Method::GET, local_var_uri_str.as_str());

    if let Some(ref local_var_str) = limit {
        local_var_req_builder = local_var_req_builder.query(&[("limit", &local_var_str.to_string())]);
    }
    if let Some(ref local_var_str) = offset {
        local_var_req_builder = local_var_req_builder.query(&[("offset", &local_var_str.to_string())]);
    }
    if let Some(ref local_var_str) = linked_object {
        local_var_req_builder = local_var_req_builder.query(&[("linked_object", &local_var_str.to_string())]);
    }
    if let Some(ref local_var_str) = linked_record_id {
        local_var_req_builder = local_var_req_builder.query(&[("linked_record_id", &local_var_str.to_string())]);
    }
    if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
        local_var_req_builder = local_var_req_builder.header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
    }
    if let Some(ref local_var_token) = local_var_configuration.oauth_access_token {
        local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
    };

    let local_var_req = local_var_req_builder.build()?;
    let local_var_resp = local_var_client.execute(local_var_req).await?;

    let local_var_status = local_var_resp.status();
    let local_var_content = local_var_resp.text().await?;

    if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
        serde_json::from_str(&local_var_content).map_err(Error::from)
    } else {
        let local_var_entity: Option<V2TasksGetError> = serde_json::from_str(&local_var_content).ok();
        let local_var_error = ResponseContent { status: local_var_status, content: local_var_content, entity: local_var_entity };
        Err(Error::ResponseError(local_var_error))
    }
}

/// Creates a new task.  At present, tasks can only be created from plaintext without record reference formatting.  Required scopes: `task:read-write`, `object_configuration:read`, `record_permission:read`, `user_management:read`.
pub async fn v2_tasks_post(configuration: &configuration::Configuration, params: V2TasksPostParams) -> Result<crate::models::V2TasksPost200Response, Error<V2TasksPostError>> {
    let local_var_configuration = configuration;

    // unbox the parameters
    let v2_tasks_post_request = params.v2_tasks_post_request;


    let local_var_client = &local_var_configuration.client;

    let local_var_uri_str = format!("{}/v2/tasks", local_var_configuration.base_path);
    let mut local_var_req_builder = local_var_client.request(reqwest::Method::POST, local_var_uri_str.as_str());

    if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
        local_var_req_builder = local_var_req_builder.header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
    }
    if let Some(ref local_var_token) = local_var_configuration.oauth_access_token {
        local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
    };
    local_var_req_builder = local_var_req_builder.json(&v2_tasks_post_request);

    let local_var_req = local_var_req_builder.build()?;
    let local_var_resp = local_var_client.execute(local_var_req).await?;

    let local_var_status = local_var_resp.status();
    let local_var_content = local_var_resp.text().await?;

    if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
        serde_json::from_str(&local_var_content).map_err(Error::from)
    } else {
        let local_var_entity: Option<V2TasksPostError> = serde_json::from_str(&local_var_content).ok();
        let local_var_error = ResponseContent { status: local_var_status, content: local_var_content, entity: local_var_entity };
        Err(Error::ResponseError(local_var_error))
    }
}

/// Delete a task by ID.  Required scopes: `task:read-write`.
pub async fn v2_tasks_task_id_delete(configuration: &configuration::Configuration, params: V2TasksTaskIdDeleteParams) -> Result<serde_json::Value, Error<V2TasksTaskIdDeleteError>> {
    let local_var_configuration = configuration;

    // unbox the parameters
    let task_id = params.task_id;


    let local_var_client = &local_var_configuration.client;

    let local_var_uri_str = format!("{}/v2/tasks/{task_id}", local_var_configuration.base_path, task_id=crate::apis::urlencode(task_id));
    let mut local_var_req_builder = local_var_client.request(reqwest::Method::DELETE, local_var_uri_str.as_str());

    if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
        local_var_req_builder = local_var_req_builder.header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
    }
    if let Some(ref local_var_token) = local_var_configuration.oauth_access_token {
        local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
    };

    let local_var_req = local_var_req_builder.build()?;
    let local_var_resp = local_var_client.execute(local_var_req).await?;

    let local_var_status = local_var_resp.status();
    let local_var_content = local_var_resp.text().await?;

    if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
        serde_json::from_str(&local_var_content).map_err(Error::from)
    } else {
        let local_var_entity: Option<V2TasksTaskIdDeleteError> = serde_json::from_str(&local_var_content).ok();
        let local_var_error = ResponseContent { status: local_var_status, content: local_var_content, entity: local_var_entity };
        Err(Error::ResponseError(local_var_error))
    }
}

/// Get a single task by ID.  Required scopes: `task:read`, `object_configuration:read`, `record_permission:read`, `user_management:read`.
pub async fn v2_tasks_task_id_get(configuration: &configuration::Configuration, params: V2TasksTaskIdGetParams) -> Result<crate::models::V2TasksPost200Response, Error<V2TasksTaskIdGetError>> {
    let local_var_configuration = configuration;

    // unbox the parameters
    let task_id = params.task_id;


    let local_var_client = &local_var_configuration.client;

    let local_var_uri_str = format!("{}/v2/tasks/{task_id}", local_var_configuration.base_path, task_id=crate::apis::urlencode(task_id));
    let mut local_var_req_builder = local_var_client.request(reqwest::Method::GET, local_var_uri_str.as_str());

    if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
        local_var_req_builder = local_var_req_builder.header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
    }
    if let Some(ref local_var_token) = local_var_configuration.oauth_access_token {
        local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
    };

    let local_var_req = local_var_req_builder.build()?;
    let local_var_resp = local_var_client.execute(local_var_req).await?;

    let local_var_status = local_var_resp.status();
    let local_var_content = local_var_resp.text().await?;

    if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
        serde_json::from_str(&local_var_content).map_err(Error::from)
    } else {
        let local_var_entity: Option<V2TasksTaskIdGetError> = serde_json::from_str(&local_var_content).ok();
        let local_var_error = ResponseContent { status: local_var_status, content: local_var_content, entity: local_var_entity };
        Err(Error::ResponseError(local_var_error))
    }
}

