/*
 * Attio API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@attio.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct V2ObjectsObjectRecordsRecordIdEntriesGet200ResponseDataInner {
    /// A UUID identifying the list that this record is in.
    #[serde(rename = "list_id")]
    pub list_id: uuid::Uuid,
    /// A human-readable slug for the list for use in URLs and responses.
    #[serde(rename = "list_api_slug")]
    pub list_api_slug: String,
    /// A UUID identifying this entry on the list.
    #[serde(rename = "entry_id")]
    pub entry_id: uuid::Uuid,
    /// When this entry was created.
    #[serde(rename = "created_at")]
    pub created_at: String,
}

impl V2ObjectsObjectRecordsRecordIdEntriesGet200ResponseDataInner {
    pub fn new(list_id: uuid::Uuid, list_api_slug: String, entry_id: uuid::Uuid, created_at: String) -> V2ObjectsObjectRecordsRecordIdEntriesGet200ResponseDataInner {
        V2ObjectsObjectRecordsRecordIdEntriesGet200ResponseDataInner {
            list_id,
            list_api_slug,
            entry_id,
            created_at,
        }
    }
}


