/*
 * Attio API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@attio.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct V2ObjectsObjectPatchRequestData {
    /// A unique, human-readable slug to access the object through URLs and API calls. Should be formatted in snake case.
    #[serde(rename = "api_slug", skip_serializing_if = "Option::is_none")]
    pub api_slug: Option<String>,
    /// The singular form of the object's name.
    #[serde(rename = "singular_noun", skip_serializing_if = "Option::is_none")]
    pub singular_noun: Option<String>,
    /// The plural form of the object's name.
    #[serde(rename = "plural_noun", skip_serializing_if = "Option::is_none")]
    pub plural_noun: Option<String>,
}

impl V2ObjectsObjectPatchRequestData {
    pub fn new() -> V2ObjectsObjectPatchRequestData {
        V2ObjectsObjectPatchRequestData {
            api_slug: None,
            singular_noun: None,
            plural_noun: None,
        }
    }
}


