/*
 * Attio API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@attio.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct V2WebhooksGet200ResponseDataInnerId {
    /// The ID of the workspace the webhook belongs to.
    #[serde(rename = "workspace_id")]
    pub workspace_id: uuid::Uuid,
    /// The ID of the webhook.
    #[serde(rename = "webhook_id")]
    pub webhook_id: uuid::Uuid,
}

impl V2WebhooksGet200ResponseDataInnerId {
    pub fn new(workspace_id: uuid::Uuid, webhook_id: uuid::Uuid) -> V2WebhooksGet200ResponseDataInnerId {
        V2WebhooksGet200ResponseDataInnerId {
            workspace_id,
            webhook_id,
        }
    }
}


