/*
 * Attio API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@attio.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct V2TargetIdentifierAttributesPostRequestDataDefaultValueOneOfTemplate {
}

impl V2TargetIdentifierAttributesPostRequestDataDefaultValueOneOfTemplate {
    pub fn new() -> V2TargetIdentifierAttributesPostRequestDataDefaultValueOneOfTemplate {
        V2TargetIdentifierAttributesPostRequestDataDefaultValueOneOfTemplate {
        }
    }
}


