/*
 * Attio API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@attio.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct V2WebhooksPostRequestData {
    /// URL where the webhook events will be delivered to.
    #[serde(rename = "target_url")]
    pub target_url: String,
    #[serde(rename = "subscriptions")]
    pub subscriptions: Vec<crate::models::V2WebhooksGet200ResponseDataInnerSubscriptionsInner>,
}

impl V2WebhooksPostRequestData {
    pub fn new(target_url: String, subscriptions: Vec<crate::models::V2WebhooksGet200ResponseDataInnerSubscriptionsInner>) -> V2WebhooksPostRequestData {
        V2WebhooksPostRequestData {
            target_url,
            subscriptions,
        }
    }
}


