/*
 * Attio API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@attio.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct V2ObjectsObjectRecordsQueryPost200ResponseDataInner {
    #[serde(rename = "id")]
    pub id: Box<crate::models::V2ObjectsObjectRecordsQueryPost200ResponseDataInnerId>,
    /// When this record was created.
    #[serde(rename = "created_at")]
    pub created_at: String,
    /// A record type with an attribute `api_slug` as the key, and an array of value objects as the values.
    #[serde(rename = "values", deserialize_with = "Option::deserialize")]
    pub values: Option<::std::collections::HashMap<String, serde_json::Value>>,
}

impl V2ObjectsObjectRecordsQueryPost200ResponseDataInner {
    pub fn new(id: crate::models::V2ObjectsObjectRecordsQueryPost200ResponseDataInnerId, created_at: String, values: Option<::std::collections::HashMap<String, serde_json::Value>>) -> V2ObjectsObjectRecordsQueryPost200ResponseDataInner {
        V2ObjectsObjectRecordsQueryPost200ResponseDataInner {
            id: Box::new(id),
            created_at,
            values,
        }
    }
}


