/*
 * Attio API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@attio.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct V2ListsListEntriesQueryPost200ResponseDataInner {
    #[serde(rename = "id")]
    pub id: Box<crate::models::V2ListsListEntriesQueryPost200ResponseDataInnerId>,
    /// A UUID identifying the record that is parent of the list entry.
    #[serde(rename = "parent_record_id")]
    pub parent_record_id: uuid::Uuid,
    /// A UUID or slug identifying the object that the parent record belongs to.
    #[serde(rename = "parent_object")]
    pub parent_object: String,
    /// When this entry was created.
    #[serde(rename = "created_at")]
    pub created_at: String,
    /// A list of attribute values for the list entry (not attribute values for its parent record).
    #[serde(rename = "entry_values", deserialize_with = "Option::deserialize")]
    pub entry_values: Option<::std::collections::HashMap<String, serde_json::Value>>,
}

impl V2ListsListEntriesQueryPost200ResponseDataInner {
    pub fn new(id: crate::models::V2ListsListEntriesQueryPost200ResponseDataInnerId, parent_record_id: uuid::Uuid, parent_object: String, created_at: String, entry_values: Option<::std::collections::HashMap<String, serde_json::Value>>) -> V2ListsListEntriesQueryPost200ResponseDataInner {
        V2ListsListEntriesQueryPost200ResponseDataInner {
            id: Box::new(id),
            parent_record_id,
            parent_object,
            created_at,
            entry_values,
        }
    }
}


