/*
 * Attio API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@attio.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct V2ListsListEntriesPostRequestData {
    /// A UUID identifying the record you want to add to the list. The record will become the 'parent' of the created list entry.
    #[serde(rename = "parent_record_id")]
    pub parent_record_id: uuid::Uuid,
    /// A UUID or slug identifying the object that the added parent record belongs to.
    #[serde(rename = "parent_object")]
    pub parent_object: String,
    /// An object with an attribute `api_slug` or `attribute_id` as the key, and an array of value objects as the values.
    #[serde(rename = "entry_values", deserialize_with = "Option::deserialize")]
    pub entry_values: Option<::std::collections::HashMap<String, serde_json::Value>>,
}

impl V2ListsListEntriesPostRequestData {
    pub fn new(parent_record_id: uuid::Uuid, parent_object: String, entry_values: Option<::std::collections::HashMap<String, serde_json::Value>>) -> V2ListsListEntriesPostRequestData {
        V2ListsListEntriesPostRequestData {
            parent_record_id,
            parent_object,
            entry_values,
        }
    }
}


