/*
 * Attio API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@attio.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct V2ObjectsPostRequestData {
    /// A unique, human-readable slug to access the object through URLs and API calls. Should be formatted in snake case.
    #[serde(rename = "api_slug")]
    pub api_slug: String,
    /// The singular form of the object's name.
    #[serde(rename = "singular_noun")]
    pub singular_noun: String,
    /// The plural form of the object's name.
    #[serde(rename = "plural_noun")]
    pub plural_noun: String,
}

impl V2ObjectsPostRequestData {
    pub fn new(api_slug: String, singular_noun: String, plural_noun: String) -> V2ObjectsPostRequestData {
        V2ObjectsPostRequestData {
            api_slug,
            singular_noun,
            plural_noun,
        }
    }
}


