/*
 * Attio API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@attio.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct V2ListsListEntriesEntryIdPutRequestData {
    /// An object with an attribute `api_slug` or `attribute_id` as the key, and an array of value objects as the values.
    #[serde(rename = "entry_values", deserialize_with = "Option::deserialize")]
    pub entry_values: Option<::std::collections::HashMap<String, serde_json::Value>>,
}

impl V2ListsListEntriesEntryIdPutRequestData {
    pub fn new(entry_values: Option<::std::collections::HashMap<String, serde_json::Value>>) -> V2ListsListEntriesEntryIdPutRequestData {
        V2ListsListEntriesEntryIdPutRequestData {
            entry_values,
        }
    }
}


