/*
 * Attio API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@attio.com
 * Generated by: https://openapi-generator.tech
 */

/// V2ObjectsObjectRecordsRecordIdAttributesAttributeValuesGet200Response : Success

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct V2ObjectsObjectRecordsRecordIdAttributesAttributeValuesGet200Response {
    // #[serde(rename = "data")]
    // pub data: Vec<crate::models::OneOfLessThanGreaterThan>,
}

impl V2ObjectsObjectRecordsRecordIdAttributesAttributeValuesGet200Response {
    // Success
    // pub fn new(// data: Vec<crate::models::OneOfLessThanGreaterThan>,
    // ) -> V2ObjectsObjectRecordsRecordIdAttributesAttributeValuesGet200Response {
    //     // V2ObjectsObjectRecordsRecordIdAttributesAttributeValuesGet200Response { data }
    // }
}
