/*
 * Attio API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@attio.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct V2CommentsPostRequest {
    // #[serde(rename = "data", deserialize_with = "Option::deserialize")]
    // pub data: Option<Box<crate::models::AnyOfLessThanGreaterThan>>,
}

impl V2CommentsPostRequest {
    pub fn new(
        
        // data: 
        
        // Option<crate::models::AnyOfLessThanGreaterThan>
    
    ) -> V2CommentsPostRequest {
        V2CommentsPostRequest {
            // data: if let Some(x) = data {Some(Box::new(x))} else {None},
        }
    }
}


