/*
 * Attio API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@attio.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct V2ListsListEntriesQueryPost200ResponseDataInnerId {
    /// A UUID identifying the workspace this entry belongs to.
    #[serde(rename = "workspace_id")]
    pub workspace_id: uuid::Uuid,
    /// A UUID identifying the list this entry is in.
    #[serde(rename = "list_id")]
    pub list_id: uuid::Uuid,
    /// A UUID identifying this entry.
    #[serde(rename = "entry_id")]
    pub entry_id: uuid::Uuid,
}

impl V2ListsListEntriesQueryPost200ResponseDataInnerId {
    pub fn new(workspace_id: uuid::Uuid, list_id: uuid::Uuid, entry_id: uuid::Uuid) -> V2ListsListEntriesQueryPost200ResponseDataInnerId {
        V2ListsListEntriesQueryPost200ResponseDataInnerId {
            workspace_id,
            list_id,
            entry_id,
        }
    }
}


