/*
 * Attio API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@attio.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct V2ObjectsObjectRecordsQueryPost200ResponseDataInnerId {
    /// A UUID identifying the workspace this record belongs to.
    #[serde(rename = "workspace_id")]
    pub workspace_id: uuid::Uuid,
    /// A UUID identifying the object this record belongs to.
    #[serde(rename = "object_id")]
    pub object_id: uuid::Uuid,
    /// A UUID identifying this record.
    #[serde(rename = "record_id")]
    pub record_id: uuid::Uuid,
}

impl V2ObjectsObjectRecordsQueryPost200ResponseDataInnerId {
    pub fn new(workspace_id: uuid::Uuid, object_id: uuid::Uuid, record_id: uuid::Uuid) -> V2ObjectsObjectRecordsQueryPost200ResponseDataInnerId {
        V2ObjectsObjectRecordsQueryPost200ResponseDataInnerId {
            workspace_id,
            object_id,
            record_id,
        }
    }
}


