/*
 * Attio API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@attio.com
 * Generated by: https://openapi-generator.tech
 */

/// V2TargetIdentifierAttributesPostRequestDataConfigCurrency : Configuration available for attributes of type \"currency\".



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct V2TargetIdentifierAttributesPostRequestDataConfigCurrency {
    /// The ISO4217 code representing the currency that values for this attribute should be stored in.
    #[serde(rename = "default_currency_code", deserialize_with = "Option::deserialize")]
    pub default_currency_code: Option<DefaultCurrencyCode>,
    /// How the currency should be displayed across the app. \"code\" will display the ISO currency code e.g. \"USD\", \"name\" will display the localized currency name e.g. \"British pound\", \"narrowSymbol\" will display \"$1\" instead of \"US$1\" and \"symbol\" will display a localized currency symbol such as \"$\".
    #[serde(rename = "display_type", deserialize_with = "Option::deserialize")]
    pub display_type: Option<DisplayType>,
}

impl V2TargetIdentifierAttributesPostRequestDataConfigCurrency {
    /// Configuration available for attributes of type \"currency\".
    pub fn new(default_currency_code: Option<DefaultCurrencyCode>, display_type: Option<DisplayType>) -> V2TargetIdentifierAttributesPostRequestDataConfigCurrency {
        V2TargetIdentifierAttributesPostRequestDataConfigCurrency {
            default_currency_code,
            display_type,
        }
    }
}

/// The ISO4217 code representing the currency that values for this attribute should be stored in.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum DefaultCurrencyCode {
    #[serde(rename = "EUR")]
    Eur,
    #[serde(rename = "GBP")]
    Gbp,
    #[serde(rename = "USD")]
    Usd,
    #[serde(rename = "CAD")]
    Cad,
    #[serde(rename = "AUD")]
    Aud,
    #[serde(rename = "AED")]
    Aed,
    #[serde(rename = "INR")]
    Inr,
    #[serde(rename = "CHF")]
    Chf,
    #[serde(rename = "JPY")]
    Jpy,
    #[serde(rename = "CNY")]
    Cny,
}

impl Default for DefaultCurrencyCode {
    fn default() -> DefaultCurrencyCode {
        Self::Eur
    }
}
/// How the currency should be displayed across the app. \"code\" will display the ISO currency code e.g. \"USD\", \"name\" will display the localized currency name e.g. \"British pound\", \"narrowSymbol\" will display \"$1\" instead of \"US$1\" and \"symbol\" will display a localized currency symbol such as \"$\".
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum DisplayType {
    #[serde(rename = "code")]
    Code,
    #[serde(rename = "name")]
    Name,
    #[serde(rename = "narrowSymbol")]
    NarrowSymbol,
    #[serde(rename = "symbol")]
    Symbol,
}

impl Default for DisplayType {
    fn default() -> DisplayType {
        Self::Code
    }
}

