/*
 * Attio API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@attio.com
 * Generated by: https://openapi-generator.tech
 */

/// V2TargetIdentifierAttributesPost200Response : Success



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct V2TargetIdentifierAttributesPost200Response {
    #[serde(rename = "data")]
    pub data: Box<crate::models::Attribute>,
}

impl V2TargetIdentifierAttributesPost200Response {
    /// Success
    pub fn new(data: crate::models::Attribute) -> V2TargetIdentifierAttributesPost200Response {
        V2TargetIdentifierAttributesPost200Response {
            data: Box::new(data),
        }
    }
}


