/*
 * Attio API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@attio.com
 * Generated by: https://openapi-generator.tech
 */

/// V2ObjectsPost200Response : Success



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct V2ObjectsPost200Response {
    #[serde(rename = "data")]
    pub data: Box<serde_json::Value>,
}

impl V2ObjectsPost200Response {
    /// Success
    pub fn new(data: serde_json::Value) -> V2ObjectsPost200Response {
        V2ObjectsPost200Response {
            data: Box::new(data),
        }
    }
}


