/*
 * Attio API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@attio.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct V2ListsPostRequestDataWorkspaceMemberAccessInner {
    /// A UUID to identify the workspace member to grant access to.
    #[serde(rename = "workspace_member_id")]
    pub workspace_member_id: uuid::Uuid,
    /// The level of access to the list.
    #[serde(rename = "level")]
    pub level: Level,
}

impl V2ListsPostRequestDataWorkspaceMemberAccessInner {
    pub fn new(workspace_member_id: uuid::Uuid, level: Level) -> V2ListsPostRequestDataWorkspaceMemberAccessInner {
        V2ListsPostRequestDataWorkspaceMemberAccessInner {
            workspace_member_id,
            level,
        }
    }
}

/// The level of access to the list.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Level {
    #[serde(rename = "full-access")]
    FullAccess,
    #[serde(rename = "read-and-write")]
    ReadAndWrite,
    #[serde(rename = "read-only")]
    ReadOnly,
}

impl Default for Level {
    fn default() -> Level {
        Self::FullAccess
    }
}

