/*
 * Attio API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@attio.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct V2TargetIdentifierAttributesPostRequestDataConfig {
    #[serde(rename = "currency", skip_serializing_if = "Option::is_none")]
    pub currency: Option<Box<crate::models::V2TargetIdentifierAttributesPostRequestDataConfigCurrency>>,
    #[serde(rename = "record_reference", skip_serializing_if = "Option::is_none")]
    pub record_reference: Option<Box<crate::models::V2TargetIdentifierAttributesPostRequestDataConfigRecordReference>>,
}

impl V2TargetIdentifierAttributesPostRequestDataConfig {
    pub fn new() -> V2TargetIdentifierAttributesPostRequestDataConfig {
        V2TargetIdentifierAttributesPostRequestDataConfig {
            currency: None,
            record_reference: None,
        }
    }
}


