/*
 * Attio API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@attio.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct V2TargetIdentifierAttributesAttributeOptionsOptionPatchRequestData {
    /// The Title of the select option
    #[serde(rename = "title", skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    /// Whether or not to archive the select option. See our [archiving guide](/docs/archiving-vs-deleting) for more information on archiving.
    #[serde(rename = "is_archived", skip_serializing_if = "Option::is_none")]
    pub is_archived: Option<bool>,
}

impl V2TargetIdentifierAttributesAttributeOptionsOptionPatchRequestData {
    pub fn new() -> V2TargetIdentifierAttributesAttributeOptionsOptionPatchRequestData {
        V2TargetIdentifierAttributesAttributeOptionsOptionPatchRequestData {
            title: None,
            is_archived: None,
        }
    }
}


