/*
 * Attio API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@attio.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct V2TargetIdentifierAttributesAttributeStatusesPostRequestData {
    /// The Title of the status
    #[serde(rename = "title")]
    pub title: String,
    /// Whether arriving at this status triggers a celebration effect
    #[serde(rename = "celebration_enabled", skip_serializing_if = "Option::is_none")]
    pub celebration_enabled: Option<bool>,
    /// Target time for a record to spend in given status expressed as a ISO-8601 duration string
    #[serde(rename = "target_time_in_status", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub target_time_in_status: Option<Option<String>>,
}

impl V2TargetIdentifierAttributesAttributeStatusesPostRequestData {
    pub fn new(title: String) -> V2TargetIdentifierAttributesAttributeStatusesPostRequestData {
        V2TargetIdentifierAttributesAttributeStatusesPostRequestData {
            title,
            celebration_enabled: None,
            target_time_in_status: None,
        }
    }
}


