/*
 * Attio API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@attio.com
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct V2ObjectsObjectRecordsQueryPostRequest {
    /// An object used to filter results to a subset of results. See the [full guide to filtering and sorting here](/docs/filtering-and-sorting).
    #[serde(
        rename = "filter",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub filter: Option<Option<::std::collections::HashMap<String, serde_json::Value>>>,
    // #[serde(rename = "sorts", skip_serializing_if = "Option::is_none")]
    // pub sorts: Option<Vec<crate::models::AnyOfLessThanGreaterThan>>,
    /// The maximum number of results to return. Defaults to 500. See the [full guide to pagination here](/docs/pagination).
    #[serde(rename = "limit", skip_serializing_if = "Option::is_none")]
    pub limit: Option<f32>,
    /// The number of results to skip over before returning. Defaults to 0. See the [full guide to pagination here](/docs/pagination).
    #[serde(rename = "offset", skip_serializing_if = "Option::is_none")]
    pub offset: Option<f32>,
}

impl V2ObjectsObjectRecordsQueryPostRequest {
    pub fn new() -> V2ObjectsObjectRecordsQueryPostRequest {
        V2ObjectsObjectRecordsQueryPostRequest {
            filter: None,
            // sorts: None,
            limit: None,
            offset: None,
        }
    }
}
