/*
 * Attio API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@attio.com
 * Generated by: https://openapi-generator.tech
 */

/// AttributeConfig : Additional, type-dependent configuration for the attribute.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct AttributeConfig {
    #[serde(rename = "currency")]
    pub currency: Box<crate::models::AttributeConfigCurrency>,
    #[serde(rename = "record_reference")]
    pub record_reference: Box<crate::models::AttributeConfigRecordReference>,
}

impl AttributeConfig {
    /// Additional, type-dependent configuration for the attribute.
    pub fn new(currency: crate::models::AttributeConfigCurrency, record_reference: crate::models::AttributeConfigRecordReference) -> AttributeConfig {
        AttributeConfig {
            currency: Box::new(currency),
            record_reference: Box::new(record_reference),
        }
    }
}


