/*
 * Attio API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@attio.com
 * Generated by: https://openapi-generator.tech
 */

/// AttributeRelationship : If this attribute is related to another attribute, this is an object that includes an `id` property that identifies the other attribute. `null` means no relationship exists. See [the help center](https://attio.com/help/reference/managing-your-data/attributes#relationship-attributes) for more details about relationship attributes.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct AttributeRelationship {
    #[serde(rename = "id")]
    pub id: Box<crate::models::AttributeId>,
}

impl AttributeRelationship {
    /// If this attribute is related to another attribute, this is an object that includes an `id` property that identifies the other attribute. `null` means no relationship exists. See [the help center](https://attio.com/help/reference/managing-your-data/attributes#relationship-attributes) for more details about relationship attributes.
    pub fn new(id: crate::models::AttributeId) -> AttributeRelationship {
        AttributeRelationship {
            id: Box::new(id),
        }
    }
}


