/*
 * Attio API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@attio.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct AttributeId {
    /// A UUID representing the workspace this attribute belongs to.
    #[serde(rename = "workspace_id", deserialize_with = "Option::deserialize")]
    pub workspace_id: Option<serde_json::Value>,
    /// A UUID to identify the object or list that this attribute belongs to
    #[serde(rename = "object_id", deserialize_with = "Option::deserialize")]
    pub object_id: Option<serde_json::Value>,
    /// A UUID to identify this attribute.
    #[serde(rename = "attribute_id", deserialize_with = "Option::deserialize")]
    pub attribute_id: Option<serde_json::Value>,
}

impl AttributeId {
    pub fn new(workspace_id: Option<serde_json::Value>, object_id: Option<serde_json::Value>, attribute_id: Option<serde_json::Value>) -> AttributeId {
        AttributeId {
            workspace_id,
            object_id,
            attribute_id,
        }
    }
}


