/*
 * Attio API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@attio.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct AttributeDefaultValueAnyOf {
    #[serde(rename = "type", deserialize_with = "Option::deserialize")]
    pub r#type: Option<Type>,
    #[serde(rename = "template", deserialize_with = "Option::deserialize")]
    pub template: Option<serde_json::Value>,
}

impl AttributeDefaultValueAnyOf {
    pub fn new(r#type: Option<Type>, template: Option<serde_json::Value>) -> AttributeDefaultValueAnyOf {
        AttributeDefaultValueAnyOf {
            r#type,
            template,
        }
    }
}

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "static")]
    Static,
}

impl Default for Type {
    fn default() -> Type {
        Self::Static
    }
}

