/*
 * Attio API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@attio.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CommentId {
    /// The ID of the workspace the comment belongs to.
    #[serde(rename = "workspace_id", deserialize_with = "Option::deserialize")]
    pub workspace_id: Option<serde_json::Value>,
    /// The ID of the comment.
    #[serde(rename = "comment_id", deserialize_with = "Option::deserialize")]
    pub comment_id: Option<serde_json::Value>,
}

impl CommentId {
    pub fn new(workspace_id: Option<serde_json::Value>, comment_id: Option<serde_json::Value>) -> CommentId {
        CommentId {
            workspace_id,
            comment_id,
        }
    }
}


