/*
 * Attio API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@attio.com
 * Generated by: https://openapi-generator.tech
 */

/// CommentRecord : The record the comment belongs to.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CommentRecord {
    /// The ID of the record the comment belongs to.
    #[serde(rename = "record_id", deserialize_with = "Option::deserialize")]
    pub record_id: Option<serde_json::Value>,
    /// The ID of the object the record belongs to.
    #[serde(rename = "object_id", deserialize_with = "Option::deserialize")]
    pub object_id: Option<serde_json::Value>,
}

impl CommentRecord {
    /// The record the comment belongs to.
    pub fn new(record_id: Option<serde_json::Value>, object_id: Option<serde_json::Value>) -> CommentRecord {
        CommentRecord {
            record_id,
            object_id,
        }
    }
}


