/*
 * Attio API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@attio.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InputValueAnyOf {
    /// The type of the referenced actor. Currently, only workspace members can be written into actor reference attributes. [Read more information on actor types here](/docs/actors).
    #[serde(rename = "referenced_actor_type", deserialize_with = "Option::deserialize")]
    pub referenced_actor_type: Option<ReferencedActorType>,
    /// The ID of the referenced Actor.
    #[serde(rename = "referenced_actor_id", deserialize_with = "Option::deserialize")]
    pub referenced_actor_id: Option<serde_json::Value>,
}

impl InputValueAnyOf {
    pub fn new(referenced_actor_type: Option<ReferencedActorType>, referenced_actor_id: Option<serde_json::Value>) -> InputValueAnyOf {
        InputValueAnyOf {
            referenced_actor_type,
            referenced_actor_id,
        }
    }
}

/// The type of the referenced actor. Currently, only workspace members can be written into actor reference attributes. [Read more information on actor types here](/docs/actors).
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ReferencedActorType {
    #[serde(rename = "workspace-member")]
    WorkspaceMember,
}

impl Default for ReferencedActorType {
    fn default() -> ReferencedActorType {
        Self::WorkspaceMember
    }
}

