/*
 * Attio API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@attio.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InputValueAnyOf16 {
    /// The UUID or select option title identifying the selected select option.
    #[serde(rename = "option", deserialize_with = "Option::deserialize")]
    pub option: Option<serde_json::Value>,
}

impl InputValueAnyOf16 {
    pub fn new(option: Option<serde_json::Value>) -> InputValueAnyOf16 {
        InputValueAnyOf16 {
            option,
        }
    }
}


