/*
 * Attio API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@attio.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InputValueAnyOf11 {
    /// Numbers are persisted as 64 bit floats.
    #[serde(rename = "value")]
    pub value: f32,
}

impl InputValueAnyOf11 {
    pub fn new(value: f32) -> InputValueAnyOf11 {
        InputValueAnyOf11 {
            value,
        }
    }
}


