/*
 * Attio API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@attio.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InputValueAnyOf14 {
    /// The UUID or status title identifying the selected status.
    #[serde(rename = "status", deserialize_with = "Option::deserialize")]
    pub status: Option<serde_json::Value>,
}

impl InputValueAnyOf14 {
    pub fn new(status: Option<serde_json::Value>) -> InputValueAnyOf14 {
        InputValueAnyOf14 {
            status,
        }
    }
}


