/*
 * Attio API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@attio.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InputValueAnyOf7 {
    /// A UUID or slug to identify the object that the referenced record belongs to.
    #[serde(rename = "target_object")]
    pub target_object: String,
    /// A UUID to identify the referenced record.
    #[serde(rename = "target_record_id", deserialize_with = "Option::deserialize")]
    pub target_record_id: Option<serde_json::Value>,
}

impl InputValueAnyOf7 {
    pub fn new(target_object: String, target_record_id: Option<serde_json::Value>) -> InputValueAnyOf7 {
        InputValueAnyOf7 {
            target_object,
            target_record_id,
        }
    }
}


