/*
 * Attio API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@attio.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InputValueAnyOf3 {
    /// A numerical representation of the currency value. A decimal with a max of 4 decimal places.
    #[serde(rename = "currency_value", deserialize_with = "Option::deserialize")]
    pub currency_value: Option<serde_json::Value>,
}

impl InputValueAnyOf3 {
    pub fn new(currency_value: Option<serde_json::Value>) -> InputValueAnyOf3 {
        InputValueAnyOf3 {
            currency_value,
        }
    }
}


