/*
 * Attio API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@attio.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InputValueAnyOf1 {
    /// Workspace member actors can be referenced by email address as well as actor ID.
    #[serde(rename = "workspace_member_email_address", deserialize_with = "Option::deserialize")]
    pub workspace_member_email_address: Option<serde_json::Value>,
}

impl InputValueAnyOf1 {
    pub fn new(workspace_member_email_address: Option<serde_json::Value>) -> InputValueAnyOf1 {
        InputValueAnyOf1 {
            workspace_member_email_address,
        }
    }
}


