/*
 * Attio API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@attio.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InputValueAnyOf17 {
    /// A raw text field. Values are limited to 10MB.
    #[serde(rename = "value", deserialize_with = "Option::deserialize")]
    pub value: Option<serde_json::Value>,
}

impl InputValueAnyOf17 {
    pub fn new(value: Option<serde_json::Value>) -> InputValueAnyOf17 {
        InputValueAnyOf17 {
            value,
        }
    }
}


