/*
 * Attio API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@attio.com
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InputValueAnyOf8 {
    /// A UUID or slug to identify the object that the referenced record belongs to.
    #[serde(rename = "target_object")]
    pub target_object: String,
    // #[serde(rename = "[slug_or_id_of_matching_attribute]")]
    // pub left_square_bracket_slug_or_id_of_matching_attribute_right_square_bracket: Vec<crate::models::AnyOfLessThanGreaterThan>,
}

impl InputValueAnyOf8 {
    pub fn new(
        target_object: String,
        // left_square_bracket_slug_or_id_of_matching_attribute_right_square_bracket: Vec<
        //     crate::models::AnyOfLessThanGreaterThan,
        // >,
    ) -> InputValueAnyOf8 {
        InputValueAnyOf8 {
            target_object,
            // left_square_bracket_slug_or_id_of_matching_attribute_right_square_bracket,
        }
    }
}
