/*
 * Attio API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@attio.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InputValueAnyOf5 {
    /// The full domain of the website.
    #[serde(rename = "domain", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub domain: Option<Option<serde_json::Value>>,
}

impl InputValueAnyOf5 {
    pub fn new() -> InputValueAnyOf5 {
        InputValueAnyOf5 {
            domain: None,
        }
    }
}


