/*
 * Attio API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@attio.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InputValueAnyOf15 {
    /// A number between 0 and 5 (inclusive) to represent a star rating.
    #[serde(rename = "value", deserialize_with = "Option::deserialize")]
    pub value: Option<serde_json::Value>,
}

impl InputValueAnyOf15 {
    pub fn new(value: Option<serde_json::Value>) -> InputValueAnyOf15 {
        InputValueAnyOf15 {
            value,
        }
    }
}


