/*
 * Attio API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@attio.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListId {
    /// A UUID to identify the workspace this list belongs to.
    #[serde(rename = "workspace_id", deserialize_with = "Option::deserialize")]
    pub workspace_id: Option<serde_json::Value>,
    /// A UUID to identify this list.
    #[serde(rename = "list_id", deserialize_with = "Option::deserialize")]
    pub list_id: Option<serde_json::Value>,
}

impl ListId {
    pub fn new(workspace_id: Option<serde_json::Value>, list_id: Option<serde_json::Value>) -> ListId {
        ListId {
            workspace_id,
            list_id,
        }
    }
}


