/*
 * Attio API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@attio.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct List {
    #[serde(rename = "id")]
    pub id: Box<crate::models::ListId>,
    /// A human-readable slug for use in URLs and responses.
    #[serde(rename = "api_slug", deserialize_with = "Option::deserialize")]
    pub api_slug: Option<serde_json::Value>,
    /// The name of the list, as viewed in the UI.
    #[serde(rename = "name", deserialize_with = "Option::deserialize")]
    pub name: Option<serde_json::Value>,
    /// A UUID or slug to identify the allowed object type for records added to this list. All new Lists are expected to have exactly one parent object. However, some legacy lists may have multiple allowed parents so the return type of this field is an array.
    #[serde(rename = "parent_object", deserialize_with = "Option::deserialize")]
    pub parent_object: Option<serde_json::Value>,
    /// The level of access granted to all members of the workspace for this list. `null` values represent a private list that only grants access to specific workspace members via the `workspace_member_access` property.
    #[serde(rename = "workspace_access", deserialize_with = "Option::deserialize")]
    pub workspace_access: Option<WorkspaceAccess>,
    /// The level of access granted to specific workspace members for this list. An empty array represents a list that has granted access to no workspace members.
    #[serde(rename = "workspace_member_access", deserialize_with = "Option::deserialize")]
    pub workspace_member_access: Option<serde_json::Value>,
    #[serde(rename = "created_by_actor")]
    pub created_by_actor: Box<crate::models::ListCreatedByActor>,
    /// When the list was created.
    #[serde(rename = "created_at", deserialize_with = "Option::deserialize")]
    pub created_at: Option<serde_json::Value>,
}

impl List {
    pub fn new(id: crate::models::ListId, api_slug: Option<serde_json::Value>, name: Option<serde_json::Value>, parent_object: Option<serde_json::Value>, workspace_access: Option<WorkspaceAccess>, workspace_member_access: Option<serde_json::Value>, created_by_actor: crate::models::ListCreatedByActor, created_at: Option<serde_json::Value>) -> List {
        List {
            id: Box::new(id),
            api_slug,
            name,
            parent_object,
            workspace_access,
            workspace_member_access,
            created_by_actor: Box::new(created_by_actor),
            created_at,
        }
    }
}

/// The level of access granted to all members of the workspace for this list. `null` values represent a private list that only grants access to specific workspace members via the `workspace_member_access` property.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum WorkspaceAccess {
    #[serde(rename = "full-access")]
    FullAccess,
    #[serde(rename = "read-and-write")]
    ReadAndWrite,
    #[serde(rename = "read-only")]
    ReadOnly,
}

impl Default for WorkspaceAccess {
    fn default() -> WorkspaceAccess {
        Self::FullAccess
    }
}

