/*
 * Attio API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@attio.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Note {
    #[serde(rename = "id")]
    pub id: Box<crate::models::NoteId>,
    /// The slug or ID of the parent object the note belongs to.
    #[serde(rename = "parent_object", deserialize_with = "Option::deserialize")]
    pub parent_object: Option<serde_json::Value>,
    /// The ID of the parent record the note belongs to.
    #[serde(rename = "parent_record_id", deserialize_with = "Option::deserialize")]
    pub parent_record_id: Option<serde_json::Value>,
    /// The note title. The title is plaintext only and has no formatting.
    #[serde(rename = "title", deserialize_with = "Option::deserialize")]
    pub title: Option<serde_json::Value>,
    /// The plaintext representation of the note content. The line feed character `\\n` represents new lines within the note content.
    #[serde(rename = "content_plaintext", deserialize_with = "Option::deserialize")]
    pub content_plaintext: Option<serde_json::Value>,
    #[serde(rename = "created_by_actor")]
    pub created_by_actor: Box<crate::models::NoteCreatedByActor>,
    /// When the note was created.
    #[serde(rename = "created_at", deserialize_with = "Option::deserialize")]
    pub created_at: Option<serde_json::Value>,
}

impl Note {
    pub fn new(id: crate::models::NoteId, parent_object: Option<serde_json::Value>, parent_record_id: Option<serde_json::Value>, title: Option<serde_json::Value>, content_plaintext: Option<serde_json::Value>, created_by_actor: crate::models::NoteCreatedByActor, created_at: Option<serde_json::Value>) -> Note {
        Note {
            id: Box::new(id),
            parent_object,
            parent_record_id,
            title,
            content_plaintext,
            created_by_actor: Box::new(created_by_actor),
            created_at,
        }
    }
}


