/*
 * Attio API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@attio.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct NoteId {
    /// The ID of the workspace the note belongs to.
    #[serde(rename = "workspace_id", deserialize_with = "Option::deserialize")]
    pub workspace_id: Option<serde_json::Value>,
    /// The ID of the note.
    #[serde(rename = "note_id", deserialize_with = "Option::deserialize")]
    pub note_id: Option<serde_json::Value>,
}

impl NoteId {
    pub fn new(workspace_id: Option<serde_json::Value>, note_id: Option<serde_json::Value>) -> NoteId {
        NoteId {
            workspace_id,
            note_id,
        }
    }
}


