/*
 * Attio API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@attio.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Object {
    #[serde(rename = "id")]
    pub id: Box<crate::models::ObjectId>,
    /// A unique, human-readable slug to access the object through URLs and API calls. Formatted in snake case.
    #[serde(rename = "api_slug", deserialize_with = "Option::deserialize")]
    pub api_slug: Option<serde_json::Value>,
    /// The singular form of the object's name.
    #[serde(rename = "singular_noun", deserialize_with = "Option::deserialize")]
    pub singular_noun: Option<serde_json::Value>,
    /// The plural form of the object's name.
    #[serde(rename = "plural_noun", deserialize_with = "Option::deserialize")]
    pub plural_noun: Option<serde_json::Value>,
    /// When the object was created.
    #[serde(rename = "created_at", deserialize_with = "Option::deserialize")]
    pub created_at: Option<serde_json::Value>,
}

impl Object {
    pub fn new(id: crate::models::ObjectId, api_slug: Option<serde_json::Value>, singular_noun: Option<serde_json::Value>, plural_noun: Option<serde_json::Value>, created_at: Option<serde_json::Value>) -> Object {
        Object {
            id: Box::new(id),
            api_slug,
            singular_noun,
            plural_noun,
            created_at,
        }
    }
}


