/*
 * Attio API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@attio.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ObjectId {
    /// A UUID to identify the workspace this object belongs to.
    #[serde(rename = "workspace_id", deserialize_with = "Option::deserialize")]
    pub workspace_id: Option<serde_json::Value>,
    /// A UUID to identify the object.
    #[serde(rename = "object_id", deserialize_with = "Option::deserialize")]
    pub object_id: Option<serde_json::Value>,
}

impl ObjectId {
    pub fn new(workspace_id: Option<serde_json::Value>, object_id: Option<serde_json::Value>) -> ObjectId {
        ObjectId {
            workspace_id,
            object_id,
        }
    }
}


