/*
 * Attio API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@attio.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct OutputValueAnyOf5 {
    #[serde(rename = "original_email_address", deserialize_with = "Option::deserialize")]
    pub original_email_address: Option<serde_json::Value>,
    #[serde(rename = "email_address", deserialize_with = "Option::deserialize")]
    pub email_address: Option<serde_json::Value>,
    #[serde(rename = "email_domain", deserialize_with = "Option::deserialize")]
    pub email_domain: Option<serde_json::Value>,
    #[serde(rename = "email_root_domain", deserialize_with = "Option::deserialize")]
    pub email_root_domain: Option<serde_json::Value>,
    #[serde(rename = "email_local_specifier", deserialize_with = "Option::deserialize")]
    pub email_local_specifier: Option<serde_json::Value>,
    /// The attribute type of the value.
    #[serde(rename = "attribute_type", deserialize_with = "Option::deserialize")]
    pub attribute_type: Option<AttributeType>,
}

impl OutputValueAnyOf5 {
    pub fn new(original_email_address: Option<serde_json::Value>, email_address: Option<serde_json::Value>, email_domain: Option<serde_json::Value>, email_root_domain: Option<serde_json::Value>, email_local_specifier: Option<serde_json::Value>, attribute_type: Option<AttributeType>) -> OutputValueAnyOf5 {
        OutputValueAnyOf5 {
            original_email_address,
            email_address,
            email_domain,
            email_root_domain,
            email_local_specifier,
            attribute_type,
        }
    }
}

/// The attribute type of the value.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum AttributeType {
    #[serde(rename = "email-address")]
    EmailAddress,
}

impl Default for AttributeType {
    fn default() -> AttributeType {
        Self::EmailAddress
    }
}

