/*
 * Attio API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@attio.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct OutputValueAnyOf13 {
    #[serde(rename = "status")]
    pub status: Box<crate::models::Status>,
    /// The attribute type of the value.
    #[serde(rename = "attribute_type", deserialize_with = "Option::deserialize")]
    pub attribute_type: Option<AttributeType>,
}

impl OutputValueAnyOf13 {
    pub fn new(status: crate::models::Status, attribute_type: Option<AttributeType>) -> OutputValueAnyOf13 {
        OutputValueAnyOf13 {
            status: Box::new(status),
            attribute_type,
        }
    }
}

/// The attribute type of the value.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum AttributeType {
    #[serde(rename = "status")]
    Status,
}

impl Default for AttributeType {
    fn default() -> AttributeType {
        Self::Status
    }
}

