/*
 * Attio API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@attio.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct OutputValueAnyOf10 {
    /// The first name.
    #[serde(rename = "first_name", deserialize_with = "Option::deserialize")]
    pub first_name: Option<serde_json::Value>,
    /// The last name.
    #[serde(rename = "last_name", deserialize_with = "Option::deserialize")]
    pub last_name: Option<serde_json::Value>,
    /// The full name.
    #[serde(rename = "full_name", deserialize_with = "Option::deserialize")]
    pub full_name: Option<serde_json::Value>,
    /// The attribute type of the value.
    #[serde(rename = "attribute_type", deserialize_with = "Option::deserialize")]
    pub attribute_type: Option<AttributeType>,
}

impl OutputValueAnyOf10 {
    pub fn new(first_name: Option<serde_json::Value>, last_name: Option<serde_json::Value>, full_name: Option<serde_json::Value>, attribute_type: Option<AttributeType>) -> OutputValueAnyOf10 {
        OutputValueAnyOf10 {
            first_name,
            last_name,
            full_name,
            attribute_type,
        }
    }
}

/// The attribute type of the value.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum AttributeType {
    #[serde(rename = "personal-name")]
    PersonalName,
}

impl Default for AttributeType {
    fn default() -> AttributeType {
        Self::PersonalName
    }
}

