/*
 * Attio API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@attio.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct OutputValueAnyOf6 {
    /// A slug identifying the object that the referenced record belongs to.
    #[serde(rename = "target_object", deserialize_with = "Option::deserialize")]
    pub target_object: Option<serde_json::Value>,
    /// A UUID to identify the referenced record.
    #[serde(rename = "target_record_id", deserialize_with = "Option::deserialize")]
    pub target_record_id: Option<serde_json::Value>,
    /// The attribute type of the value.
    #[serde(rename = "attribute_type", deserialize_with = "Option::deserialize")]
    pub attribute_type: Option<AttributeType>,
}

impl OutputValueAnyOf6 {
    pub fn new(target_object: Option<serde_json::Value>, target_record_id: Option<serde_json::Value>, attribute_type: Option<AttributeType>) -> OutputValueAnyOf6 {
        OutputValueAnyOf6 {
            target_object,
            target_record_id,
            attribute_type,
        }
    }
}

/// The attribute type of the value.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum AttributeType {
    #[serde(rename = "record-reference")]
    RecordReference,
}

impl Default for AttributeType {
    fn default() -> AttributeType {
        Self::RecordReference
    }
}

