/*
 * Attio API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@attio.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct SelectOption {
    #[serde(rename = "id")]
    pub id: Box<crate::models::SelectOptionId>,
    /// The title of the select option
    #[serde(rename = "title", deserialize_with = "Option::deserialize")]
    pub title: Option<serde_json::Value>,
    /// Whether or not to archive the select option. See our [archiving guide](/docs/archiving-vs-deleting) for more information on archiving.
    #[serde(rename = "is_archived", deserialize_with = "Option::deserialize")]
    pub is_archived: Option<serde_json::Value>,
}

impl SelectOption {
    pub fn new(id: crate::models::SelectOptionId, title: Option<serde_json::Value>, is_archived: Option<serde_json::Value>) -> SelectOption {
        SelectOption {
            id: Box::new(id),
            title,
            is_archived,
        }
    }
}


