/*
 * Attio API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@attio.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct SelectOptionId {
    /// The ID of the workspace
    #[serde(rename = "workspace_id", deserialize_with = "Option::deserialize")]
    pub workspace_id: Option<serde_json::Value>,
    /// The ID of the object
    #[serde(rename = "object_id", deserialize_with = "Option::deserialize")]
    pub object_id: Option<serde_json::Value>,
    /// The ID of the attribute
    #[serde(rename = "attribute_id", deserialize_with = "Option::deserialize")]
    pub attribute_id: Option<serde_json::Value>,
    /// The ID of the select option
    #[serde(rename = "option_id", deserialize_with = "Option::deserialize")]
    pub option_id: Option<serde_json::Value>,
}

impl SelectOptionId {
    pub fn new(workspace_id: Option<serde_json::Value>, object_id: Option<serde_json::Value>, attribute_id: Option<serde_json::Value>, option_id: Option<serde_json::Value>) -> SelectOptionId {
        SelectOptionId {
            workspace_id,
            object_id,
            attribute_id,
            option_id,
        }
    }
}


