/*
 * Attio API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@attio.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Status {
    #[serde(rename = "id")]
    pub id: Box<crate::models::StatusId>,
    /// The title of the status
    #[serde(rename = "title", deserialize_with = "Option::deserialize")]
    pub title: Option<serde_json::Value>,
    /// Whether or not to archive the status. See our [archiving guide](/docs/archiving-vs-deleting) for more information on archiving.
    #[serde(rename = "is_archived", deserialize_with = "Option::deserialize")]
    pub is_archived: Option<serde_json::Value>,
    /// Whether arriving at this status triggers a celebration effect in the UI
    #[serde(rename = "celebration_enabled", deserialize_with = "Option::deserialize")]
    pub celebration_enabled: Option<serde_json::Value>,
    /// Target time for a record to spend in given status expressed as a ISO-8601 duration string
    #[serde(rename = "target_time_in_status", deserialize_with = "Option::deserialize")]
    pub target_time_in_status: Option<serde_json::Value>,
}

impl Status {
    pub fn new(id: crate::models::StatusId, title: Option<serde_json::Value>, is_archived: Option<serde_json::Value>, celebration_enabled: Option<serde_json::Value>, target_time_in_status: Option<serde_json::Value>) -> Status {
        Status {
            id: Box::new(id),
            title,
            is_archived,
            celebration_enabled,
            target_time_in_status,
        }
    }
}


