/*
 * Attio API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@attio.com
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Thread {
    #[serde(rename = "id")]
    pub id: Box<crate::models::ThreadId>,
    /// An array of comments in the thread, sorted by `created_at`.
    #[serde(rename = "comments", deserialize_with = "Option::deserialize")]
    pub comments: Option<serde_json::Value>,
    /// When the thread was created.
    #[serde(rename = "created_at", deserialize_with = "Option::deserialize")]
    pub created_at: Option<serde_json::Value>,
}

impl Thread {
    pub fn new(
        id: crate::models::ThreadId,
        comments: Option<serde_json::Value>,
        created_at: Option<serde_json::Value>,
    ) -> Thread {
        Thread {
            id: Box::new(id),
            comments,
            created_at,
        }
    }
}
