/*
 * Attio API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@attio.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ThreadId {
    /// The ID of the workspace the thread belongs to.
    #[serde(rename = "workspace_id", deserialize_with = "Option::deserialize")]
    pub workspace_id: Option<serde_json::Value>,
    /// The ID of the thread.
    #[serde(rename = "thread_id", deserialize_with = "Option::deserialize")]
    pub thread_id: Option<serde_json::Value>,
}

impl ThreadId {
    pub fn new(workspace_id: Option<serde_json::Value>, thread_id: Option<serde_json::Value>) -> ThreadId {
        ThreadId {
            workspace_id,
            thread_id,
        }
    }
}


