/*
 * Attio API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@attio.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct WorkspaceMemberId {
    /// The ID of the workspace the workspace member belongs to.
    #[serde(rename = "workspace_id", deserialize_with = "Option::deserialize")]
    pub workspace_id: Option<serde_json::Value>,
    /// The ID of the workspace member.
    #[serde(rename = "workspace_member_id", deserialize_with = "Option::deserialize")]
    pub workspace_member_id: Option<serde_json::Value>,
}

impl WorkspaceMemberId {
    pub fn new(workspace_id: Option<serde_json::Value>, workspace_member_id: Option<serde_json::Value>) -> WorkspaceMemberId {
        WorkspaceMemberId {
            workspace_id,
            workspace_member_id,
        }
    }
}


